<html>
    <head>
        <title>Audioeditor</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!--link rel="stylesheet" href="css/reset.css" type="text/css"-->
        <link rel="stylesheet" href="css/style.css" type="text/css">
        <link rel="stylesheet" media="all" href="css/FilesDragger.css"/>
      
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/Util.js"></script>
        <script type="text/javascript" src="js/Worktable.js"></script>
        <script type="text/javascript" src="js/VisualSample.js"></script> 
        <script type="text/javascript" src="js/Row.js"></script>
        <script type="text/javascript" src="js/FilesDragger.js"></script>
        <script type="text/javascript" src="js/jquery-ui/js/jquery-ui-1.8.18.custom.min.js"></script>
        
        
        
        <script type="text/javascript">
            
            var l = function(s) { console.log(s, Math.random());} 
            $(document).ready(function() {
                var worktable = new Worktable();
                var row = worktable.createRow();
                var row2 = worktable.createRow();
                var sample = document.getElementById('trololo');
                var sample2 = document.getElementById('trololo2');
                
                var currentDragger = new FilesDragger({
                    dropCallback: function(e) {
                        var row = e.target;
                        rowId = row.id.split('-')[1];
                        var row = worktable.getRow(rowId);
                        var sample = $(e.dataTransfer.getData('text/html'))[0];
                        l(sample.canPlayType('audio/wave'))
                        $(sample).bind('loadedmetadata',function(){
                            var offset = e.clientX - $('#row-' + row.id).offset().left - sample.duration/2 * Row.WIDTH_COEF;
                            row.addSample(sample, offset);
                         })
                    }
                });
                var files = document.querySelectorAll('#files_tree .files_item');
                [].forEach.call(files, function(file) {
                    currentDragger.initDraggable(file)
                })
                currentDragger.initDropper(document.getElementById('dropper'));
                
                
                $('#files_tree').accordion();
                $('#files_tree h').click(function() {
                $(this).next().toggle('slow');
                    return false;
                }).next().hide();
            });
        </script>
    </head>
    <body>
        <audio id="trololo" controls="controls">
            <source src="samples/1.ogg" type="audio/ogg" />
        </audio>        
        <audio id="trololo2" controls="controls">
            <source src="samples/1.ogg" type="audio/ogg" />
        </audio>
        <h1>AudioEditor</h1>
        <div class="effects">
            
        </div>
        <div class="samples">
            
        </div>
        <div class="worktable">
            <div class="rows" id="dropper"  draggable="true">
                
            </div>
            <div class="controls">
                <input class="addRow" type="button" value="Add row">
            </div>
        </div>
        <div class="completePlayer">
            
        </div>
        <div class="files_tree" id="files_tree">
           <?php echo $viewFilesTree; ?>
        </div>

        <script type="text/template" id="sample-template">
            <div class="sample" style="width: ${width}px; left: ${offset}px">
                <div class="tools">
                    <input type="slider" name="volume">
                    <div class="close">X</div>        
                </div>
                <canvas></canvas>
                ${title}
            </div>
        </script>
    </body>
</html>