<html>
    <head>
        <title>Audioeditor</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!--link rel="stylesheet" href="css/reset.css" type="text/css"-->
        <link rel="stylesheet" href="css/style.css" type="text/css">
        <link rel="stylesheet" media="all" href="css/FilesDragger.css"/>
      
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/Util.js"></script>
        <script type="text/javascript" src="js/Worktable.js"></script>
        <script type="text/javascript" src="js/VisualSample.js"></script> 
        <script type="text/javascript" src="js/Row.js"></script>
        <script type="text/javascript" src="js/FilesDragger.js"></script>
        <script type="text/javascript" src="js/html5slider.js"></script>
        <script type="text/javascript" src="js/player.js"></script>
        <script type="text/javascript" src="js/jquery-ui/js/jquery-ui-1.8.18.custom.min.js"></script>
        <script type="text/javascript">
            
            var l = function(s) { console.log(s, Math.random());} 
            $(document).ready(function() {
                var worktable = new Worktable();
                var row = worktable.createRow();
                var row2 = worktable.createRow();
                
                var player = new Player();
            
                var currentDragger = new FilesDragger({
                    dropCallback: function(e) {
                        var row;
                        if (e.originalTarget.className == 'row') {
                            row = e.target;
                        } else {
                            row = e.target.parentNode;
                        }
                        rowId = row.id.split('-')[1];
                        var row = worktable.getRow(rowId);
                        var sample = $(e.dataTransfer.getData('text/html'))[0];

                        $(sample).bind('loadedmetadata',function(){
                            var offset = e.clientX - $('#row-' + row.id).offset().left - sample.duration/2 * Row.WIDTH_COEF;
                            row.addSample(sample, offset);
                        });
                    }

                });
                $('#startPlayer').click(function() {
                    player.samples = [];
                    var samples = worktable.getSamples();
                    for (var i = 0; i < samples.length; i++) {
                        var sample = samples[i].container.data('sample');
                        var offset = samples[i].container.offset().left - sample.duration/2 * Row.WIDTH_COEF;
                            
                        var playerSample = player.addSample(sample.currentSrc, Math.round(offset/Row.PIXEL_PER_SECOND * 1000));
                        //////////////////////////////////////
                                var canvas   = $(samples[i].container).find('canvas')[0],
                                    context  = canvas.getContext('2d'),
                                    gradient = context.createLinearGradient(0, -1, 0, 1);

                            var spectrum = [
                                '#FF00FF', // 5, Magenta, 300°
                                '#0000FF', // 4, Blue,    240°
                                '#00FFFF', // 3, Cyan,    180°
                                '#00FF00', // 2, Green,   120°
                                '#FFFF00', // 1, Yellow,   60°
                                '#FF0000'  // 0, Red,       0°
                            ];
                                    
                                [1, -1].forEach(function(k) {
                                    k /= 2 * (spectrum.length - 1);
                                    spectrum.forEach(function(color, i) {
                                        gradient.addColorStop(0.5 + k * i, color);
                                    });
                                });
                                
                                context.scale(canvas.width / (sample.duration * sample.mozSampleRate), -canvas.height / 2);
                                context.translate(0, -1);
                                context.fillStyle = gradient;
                                
                                var lastPower = 0;
                                
                                $(playerSample.audio).bind('MozAudioAvailable', function(event) {
                                    mozRequestAnimationFrame(function () {
                                        var buffer = event.originalEvent.frameBuffer,
                                            bufferWidth = buffer.length;
                                        
                                        context.translate(event.originalEvent.time * sample.mozSampleRate, 0);
                                        context.beginPath();
                                        {
                                            context.moveTo(0, lastPower);
                                            for (var i = 0, x = 1; i < buffer.length; i++, x++) {
                                                context.lineTo(x, buffer[i]);
                                            }
                                            lastPower = buffer[buffer.length - 1];
                                            context.lineTo(bufferWidth, 0);
                                            context.lineTo(0, 0);
                                        }
                                        context.fill();
                                        context.translate(-event.originalEvent.time * sample.mozSampleRate, 0);
                                    });
                                });
                   /////////////////////////     
                    } 
                    player.play();
                });
                var files = document.querySelectorAll('#files_tree .files_item');
                [].forEach.call(files, function(file) {
                    currentDragger.initDraggable(file)
                })
                currentDragger.initDropper(document.getElementById('dropper'));              
                
                $('#files_tree').accordion();
                $('#files_tree h').click(function() {
                $(this).next().toggle('slow');
                    return false;
                }).next().hide();

            });
        </script>
    </head>
    <body>
        <h1>AudioEditor <input type="button" value="Play" id="startPlayer"></h1>
        <div class="effects">
            
        </div>
        <div class="samples">
            
        </div>
        <div class="worktable">
            <div class="rows" id="dropper"  draggable="true">
                
            </div>
            <div class="controls">
                <input class="addRow" type="button" value="Add row">
            </div>
        </div>
        <div class="completePlayer">
            
        </div>
        <div class="files_tree" id="files_tree">
           <?php echo $viewFilesTree; ?>
        </div>

        <script type="text/template" id="sample-template">
            <div class="sample" style="left: ${offset}px;">
                <div class="tools">
                    <input type="range" name="volume" value="100" >
                    <div class="close">X</div>        
                </div>
                <canvas style=" border-color: ${color}"></canvas>
                <span>${title}</span>
            </div>
        </script>
    </body>
</html>